SHOW TABLES;

SELECT TABLE_NAME FROM information_schema.TABLES
WHERE TABLE_SCHEMA = 'library'

SELECT * FROM `user` ORDER BY username DESC;

SELECT * FROM QnA ORDER BY id DESC;

SELECT * FROM bookRent ORDER BY id DESC;
SELECT * FROM bookReservation ORDER BY id DESC;

