SHOW TABLES;

SELECT TABLE_NAME FROM information_schema.TABLES
WHERE TABLE_SCHEMA = 'library'

SELECT * FROM `user` ORDER BY id DESC;

SELECT * FROM QnA ORDER BY id DESC;


SELECT * FROM bookrequest  ORDER BY id DESC;
SELECT * FROM file  ORDER BY id DESC;

SELECT * FROM request_comment  ORDER BY id DESC;